# Generated by Django 5.2.11 on 2026-02-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='care',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='care',
            name='date',
            field=models.DateField(default='2025-01-01', verbose_name='CARE DATE'),
            preserve_default=False,
        ),
    ]
