# Generated by Django 5.2.11 on 2026-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0003_remove_plant_categories_alter_plant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(to='plants_app.category'),
        ),
    ]
