# Generated by Django 5.2.11 on 2026-03-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0004_plant_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('N', 'Night')], max_length=2, null=True),
        ),
    ]
