# Generated by Django 5.2.11 on 2026-03-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0005_care_time_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Plant Image URL'),
        ),
    ]
