# Generated by Django 5.2.11 on 2026-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0007_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(blank=True, to='plants_app.category'),
        ),
    ]
